version: "3.8"

services:
  web:
    container_name: my_gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    networks:
      my_network:
        ipv4_address: 192.168.0.254
    hostname: '192.168.0.254'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://192.168.0.254'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

networks:
  my_network:
    attachable: true
    name: my_network
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.255/28